# Based on:
# https://github.com/ubisoft/Sharpmake/blob/main/.github/workflows/build.yml

name: Build Sharpmake

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      framework:
        required: true
        type: string
      configuration:
        required: true
        type: string

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true

jobs:
  build:
    runs-on: ${{ inputs.os }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4.2.2
        with:
          submodules: true
        
      - name: Create branch on pull request from framework
        if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork
        run: git checkout -b ${{ github.ref_name }}

      - name: Build Sharpmake ${{ inputs.configuration }} ${{ inputs.os }}
        shell: pwsh
        run: |
          dotnet build "./tools/Sharpmake/Sharpmake.sln" -c "${{ inputs.configuration }}" -bl:Sharpmake_${{ inputs.configuration }}.binlog
      
      - name: Store MSBuild binary logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sharpmake-msbuild-logs-${{ inputs.framework }}-${{ runner.os }}-${{ github.sha }}-${{ inputs.configuration }}
          path: Sharpmake_${{ inputs.configuration }}.binlog

      - name: Upload sharpmake ${{ inputs.framework }} ${{ runner.os }}-release binaries
        if: inputs.configuration == 'release'
        uses: actions/upload-artifact@v4
        with:
          name: 'Sharpmake-${{ inputs.framework }}-${{ runner.os }}-${{ github.sha }}'
          path: ./tools/Sharpmake/Sharpmake.Application/bin/Release/${{ inputs.framework }}